#!/usr/bin/env python
"""Generate SI vacancy formation energy tables and strip-plot figure.

Loads pre-computed relaxed E_vf values from the project checkpoint, excludes
two erroneous sites in Sigma9, and writes:
  - data/SI_vacancy_summary.tex   (per-GB summary table)
  - data/SI_vacancy_persite.tex   (per-site detailed table)
  - figures/SI_vacancy_formation_by_GB.png

Run from anywhere; paths are resolved relative to this file.
"""
import pickle, gzip
from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[2]
CHK = REPO / 'data' / 'checkpoints' / 'KP_Vacancy_Formation_Energy.pkl.gz'
FIG_DIR = REPO / 'figures'
TEX_DIR = REPO / 'data'

GB_ORDER = [
    'S3_RA110_S1_11', 'S3_RA110_S1_12',
    'S5_RA001_S210',  'S5_RA001_S310',
    'S9_RA110_S2_21', 'S11_RA110_S3_32',
]
GB_LATEX = {
    'S3_RA110_S1_11':  r'$\Sigma 3[1\bar{1}0](111)$',
    'S3_RA110_S1_12':  r'$\Sigma 3[1\bar{1}0](112)$',
    'S5_RA001_S210':   r'$\Sigma 5[001](210)$',
    'S5_RA001_S310':   r'$\Sigma 5[001](310)$',
    'S9_RA110_S2_21':  r'$\Sigma 9[1\bar{1}0](221)$',
    'S11_RA110_S3_32': r'$\Sigma 11[1\bar{1}0](332)$',
}
EXCLUDE = {('S9_RA110_S2_21', 0), ('S9_RA110_S2_21', 1)}


def load_vacancy_data() -> pd.DataFrame:
    with gzip.open(CHK, 'rb') as f:
        df = pickle.load(f)
    mask = df.apply(lambda r: (r['GB'], r['site']) not in EXCLUDE, axis=1)
    return df[mask].copy()


def write_summary_table(df: pd.DataFrame, path: Path) -> pd.DataFrame:
    rows = []
    for gb in GB_ORDER:
        sub = df[df['GB'] == gb]
        if len(sub) == 0:
            continue
        rows.append({
            'GB': gb, 'N': len(sub),
            'min': sub['E_vf'].min(), 'mean': sub['E_vf'].mean(),
            'median': sub['E_vf'].median(), 'max': sub['E_vf'].max(),
        })
    summary = pd.DataFrame(rows).set_index('GB')
    with path.open('w') as f:
        f.write('% Auto-generated by generate_SI_vacancy_tables.py\n')
        f.write('\\begin{tabular}{lccccc}\n\\hline\n')
        f.write('GB & $N$ & min & mean & median & max \\\\\n\\hline\n')
        for gb, r in summary.iterrows():
            f.write(f"{GB_LATEX[gb]} & {int(r['N'])} & "
                    f"{r['min']:+.3f} & {r['mean']:+.3f} & {r['median']:+.3f} & {r['max']:+.3f} \\\\\n")
        f.write('\\hline\n')
        f.write(f"\\textbf{{All}} & \\textbf{{{len(df)}}} & "
                f"\\textbf{{{df['E_vf'].min():+.3f}}} & \\textbf{{{df['E_vf'].mean():+.3f}}} & "
                f"\\textbf{{{df['E_vf'].median():+.3f}}} & \\textbf{{{df['E_vf'].max():+.3f}}} \\\\\n")
        f.write('\\hline\n\\end{tabular}\n')
    return summary


def write_persite_table(df: pd.DataFrame, path: Path) -> None:
    df_sorted = df.copy()
    df_sorted['gb_rank'] = df_sorted['GB'].map({g: i for i, g in enumerate(GB_ORDER)})
    df_sorted = df_sorted.sort_values(['gb_rank', 'site']).reset_index(drop=True)
    with path.open('w') as f:
        f.write('% Auto-generated by generate_SI_vacancy_tables.py\n')
        f.write('\\begin{tabular}{llrr}\n\\hline\n')
        f.write('GB & Site & $E_\\mathrm{vac}$ (eV) & $E_\\mathrm{vf}$ (eV) \\\\\n\\hline\n')
        for _, r in df_sorted.iterrows():
            import math
            e_vac = r['E_vac']; e_vf = r['E_vf']
            vac_str = 'FAILED' if (e_vac is None or (isinstance(e_vac, float) and math.isnan(e_vac))) else f"{e_vac:.3f}"
            vf_str  = 'FAILED' if (e_vf  is None or (isinstance(e_vf, float) and math.isnan(e_vf)))  else f"{e_vf:+.3f}"
            f.write(f"{GB_LATEX[r['GB']]} & {int(r['site'])} & {vac_str} & {vf_str} \\\\\n")
        f.write('\\hline\n\\end{tabular}\n')


def plot_strip(df: pd.DataFrame, path: Path) -> None:
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b']
    fig, ax = plt.subplots(figsize=(8, 6))
    rng = np.random.default_rng(0)
    for i, gb in enumerate(GB_ORDER):
        sub = df[df['GB'] == gb]
        if len(sub) == 0:
            continue
        x = np.full(len(sub), i) + rng.uniform(-0.18, 0.18, size=len(sub))
        ax.scatter(x, sub['E_vf'], s=60, color=colors[i], edgecolor='black',
                   linewidth=0.8, alpha=0.85, zorder=3)
        ax.plot([i-0.3, i+0.3], [sub['E_vf'].mean()]*2, color='black',
                linewidth=2.2, zorder=4)
    ax.axhline(0, color='black', linewidth=0.8, linestyle='--', alpha=0.6)
    ax.set_xticks(range(len(GB_ORDER)))
    ax.set_xticklabels([GB_LATEX[g] for g in GB_ORDER], rotation=25, ha='right', fontsize=14)
    ax.set_ylabel(r'$E_\mathrm{vf}$  (eV)', fontsize=22)
    ax.tick_params(axis='y', labelsize=18)
    ax.grid(alpha=0.25, axis='y')
    plt.tight_layout()
    fig.savefig(path, dpi=300, bbox_inches='tight')
    plt.close(fig)


def main():
    df = load_vacancy_data()
    summary = write_summary_table(df, TEX_DIR / 'SI_vacancy_summary.tex')
    write_persite_table(df, TEX_DIR / 'SI_vacancy_persite.tex')
    plot_strip(df, FIG_DIR / 'SI_vacancy_formation_by_GB.png')
    print(f'Loaded {len(df)} relaxed-vacancy sites (Sigma9 sites 0/1 excluded).')
    print(summary)
    print(f'Tables: {TEX_DIR}/SI_vacancy_summary.tex, SI_vacancy_persite.tex')
    print(f'Figure: {FIG_DIR}/SI_vacancy_formation_by_GB.png')


if __name__ == '__main__':
    main()
